### PR TITLE
Fix lnurl fallback

### LINKED ISSUE #1599: [BUG] Does not support LNURL LUD-01 Fallback Schemes
## Description

[This](https://github.com/lnurl/luds/blob/luds/01.md#fallback-scheme) seems to not be supported as yet when sending from wallet. Can test with the QR code [here](https://pay.blink.sv/vindard/print) for reference which resolves to `https://pay.blink.sv/VINDARD?LIGHTNING=LNURL1DP68GURN8GHJ7URP0YHXYMRFDE4JUUMK9UH8WETVDSKKKMN0WAHZ7MRWW4EXCUP0WE5KUERPWFJQSU3QFK`

### PR DESCRIPTION
**Pull request by talvasconcelos**
Wrong string case search

Closes #1599

### CODE REVIEW

**Review by dni — APPROVED** [review]

File: lnbits/static/js/wallet.js [hunk 1]
```diff
@@ -225,6 +225,7 @@ new Vue({
         this.parse.data.request = this.parse.data.request.slice(6)
       } else if (req.indexOf('lightning=lnurl1') !== -1) {
```
Comment (prusnak) [inline lnbits/static/js/wallet.js:226]: should we also use req.toLowerCase here?

Comment (talvasconcelos) [reply lnbits/static/js/wallet.js:226]: the variable was set, probably to avoid writing `this.parse.data.request` a few times... it wasn't used, BTW... 

could this all block code could be optimized? yes...

Comment (talvasconcelos) [reply lnbits/static/js/wallet.js]: can you check with latest commit, if it looks better? at least i think it reduces a couple lines

Comment (prusnak) [reply lnbits/static/js/wallet.js]: Yes. Looks much more clean now.

**Review by prusnak — APPROVED** [review]
