### PR TITLE
fix: vertically center first install

### LINKED ISSUE #3497: [BUG] yertically  center first_install form
Image

### PR DESCRIPTION
**Pull request by talvasconcelos**
main html tag (`<main></main>`) needs "centering"

Style is applied on the template and scoped... so it doesn't affect other tags! 

image

Closes #3497

### CODE REVIEW

**Comment by talvasconcelos** [comment]
IMHO, this is a one time page, it's fine to have the style tag with the styling... I can change it if needed! @dni @motorina0

File: lnbits/templates/pages/first-install.vue [hunk 1]
```diff
@@ -73,3 +73,11 @@
     </div>
   </div>
 </template>
+
+<style scoped>
```
Comment (dni) [inline lnbits/templates/pages/first-install.vue]: are you sure the scoped, does not work for other pages? not sure if that works because we  dont use the vue templates as we should.

Comment (talvasconcelos) [reply lnbits/templates/pages/first-install.vue]: Checking... apparently it leaks! 

Let me try another approach
